name: database_builder
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.9.1
  sqlite3: ^3.1.4
  unorm_dart: ^0.3.1+1
  scripture: ^0.4.0
  # scripture:
  #   path: ../../../scripture
    

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
